version: "3"

services:
  flask-api:
    build: .
    volumes:
      - .:/code
    environment:
      DLBAD_PYTHON_RESTAPI_ENDPOINT_KEY: ${DLBAD_PYTHON_RESTAPI_ENDPOINT_KEY}
      DLBAD_HASURA_ENDPOINT: ${DLBAD_HASURA_ENDPOINT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "6080:5000"
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    env_file:
      - .env
